name: Readme Creator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup 1/2
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup 2/2
        run: javac Generator.java
      - name: Generate README.md
        run: |
          java -cp . Generator
      - name: Commit README.md
        run: |
          git config --global user.name 'yoyosource'
          git config --global user.email 'yoyosource@users.noreply.github.com'
          set +e
          if git status | grep -E 'add|modified'
          then
            set -e
            git add --all
            git commit -am "Automatic README.md generation"
            git push
          else
            set -e
          fi
